// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	ckb_stats "github.com/Magickbase/blockchain-stats/app/datacenter/internal/handler/ckb_stats"
	"github.com/Magickbase/blockchain-stats/app/datacenter/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// /ckb_transaction_tracking
				Method:  http.MethodGet,
				Path:    "/ckb_transaction_tracking",
				Handler: ckb_stats.TransactionTrackingHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
		rest.WithTimeout(600000*time.Millisecond),
	)
}
